name: Health check

on:
  push:
    branches:
      - master

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: URL Health Check
        uses: Jtalk/url-health-check-action@v3.1
        with:
          url: https://polar-meadow-41009.herokuapp.com/